# Generated by Django 6.0.3 on 2026-03-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_ofertalaboral_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='cv',
        ),
    ]
