# Generated by Django 6.0.3 on 2026-03-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_postulacion_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
