# Generated by Django 6.0.3 on 2026-03-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
